kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name:  {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-panel-button-cleanup
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    icon: fa-trash
    type: default
    shape: circle
    clickActionId: cleanup
    actions:
      rest:
        - id: cleanup
          resourceRefId: cleanup
          type: rest
          onSuccessNavigateTo: /blueprints
          successMessage: "Successfully deleted {{ .Values.global.compositionName }} blueprint in {{ .Release.Namespace }}"
          headers:
          - "Content-Type: application/json"
  resourcesRefs:
    items:
      - id: cleanup
        apiVersion: composition.krateo.io/v{{ .Chart.Version | replace "." "-" }}
        resource: portalblueprintpages
        name:  {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}
        namespace: {{ .Release.Namespace }}
        verb: DELETE