apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name:  {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}
  namespace: {{ .Release.Namespace }}
spec:
  chart:
    {{- $url := .Values.blueprint.url }}
    {{- if not (hasPrefix "oci://" $url) }}
    repo: {{ .Values.blueprint.repo }}
    {{- end }}
    url: {{ $url | quote }}
    version: {{ .Values.blueprint.version }}
    {{- $creds := .Values.blueprint.credentials | default dict }}
    {{- if gt (len $creds) 0 }}
    credentials:
      {{- with $creds.username }}
      username: {{ . | quote }}
      {{- end }}
      {{- with $creds.passwordRef }}
      passwordRef:
        {{- with .key }}
        key: {{ . | quote }}
        {{- end }}
        {{- with .name }}
        name: {{ . | quote }}
        {{- end }}
        {{- with .namespace }}
        namespace: {{ . | quote }}
        {{- end }}
      {{- end }}
    {{- end }}