kind: Form
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name:  {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-form
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    schema:
{{- toYaml .Values.form.widgetData.schema | nindent 6 }}
    objectFields:
{{- toYaml .Values.form.widgetData.objectFields | nindent 6 }}
    submitActionId: {{ .Values.form.widgetData.submitActionId | quote }}
    actions:
      rest:
{{- range .Values.form.widgetData.actions.rest }}
        - id: {{ .id | quote }}
          onEventNavigateTo:
            eventReason: {{ .onEventNavigateTo.eventReason | quote }}
            {{- if eq $.Values.blueprint.hasPage true }}
            url: {{ .onEventNavigateTo.url }}
            {{- else }}
            url: {{ .onEventNavigateTo.urlIfNoPage | quote }}
            {{- end }}
            timeout: {{ .onEventNavigateTo.timeout }}
          successMessage: {{ .successMessage }}
          resourceRefId: {{ .resourceRefId | quote }}
          type: {{ .type | quote }}
          payloadToOverride:
{{- toYaml .payloadToOverride | nindent 12 }}
          headers:
{{- toYaml .headers | nindent 12 }}
{{- end }}
  widgetDataTemplate:
{{- range .Values.form.widgetDataTemplate }}
    - forPath: {{ .forPath | quote }}
      expression: |
{{ .expression | nindent 8 }}
{{- end }}
  resourcesRefsTemplate:
    - iterator: {{ .Values.form.resourcesRefsTemplate.iterator }}
      template:
        id: {{ .Values.form.resourcesRefsTemplate.template.id }}
        apiVersion: {{ .Values.form.resourcesRefsTemplate.template.apiVersion }} 
        namespace: {{ .Values.form.resourcesRefsTemplate.template.namespace }}
        resource: {{ .Values.form.resourcesRefsTemplate.template.resource }}
        verb: {{ .Values.form.resourcesRefsTemplate.template.verb }}
  apiRef:
    name: {{ tpl .Values.form.apiRef.name . }}
    namespace: {{ default .Release.Namespace (tpl .Values.form.apiRef.namespace .) | quote }}