{{- if eq .Values.form.hasPage true }}
kind: Page
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name:  {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-form-page
  namespace: {{ .Release.Namespace }}
spec:
  widgetData:
    allowedResources:
      - panels
    items:
      - resourceRefId: form-page-panel
  resourcesRefs:
    items:
      - id: form-page-panel
        apiVersion: widgets.templates.krateo.io/v1beta1
        name:  {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-form-page-panel
        namespace: {{ .Release.Namespace }}
        resource: panels
        verb: GET
{{- end }}