kind: Panel
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name:  {{ .Values.global.compositionKind | lower }}-{{ .Values.global.compositionName }}-panel
  namespace: {{ .Release.Namespace }}
  labels:
    krateo.io/portal-page: blueprints
spec:
  apiRef:
    name: {{ tpl .Values.panel.apiRef.name . }}
    namespace: {{ default .Release.Namespace (tpl .Values.panel.apiRef.namespace .) | quote }}

  widgetData:
    clickActionId: {{ .Values.panel.widgetData.clickActionId | quote }}
    footer:
{{- toYaml .Values.panel.widgetData.footer | nindent 6 }}
    tags:
{{- range .Values.panel.widgetData.tags }}
      - {{ tpl . $ | quote }}
{{- end }}
    icon:
      name: {{ tpl .Values.panel.widgetData.icon.name . | quote }}
    items:
{{- toYaml .Values.panel.widgetData.items | nindent 6 }}
    title: {{ tpl .Values.panel.widgetData.title . | quote }}
    actions:
      {{- if eq .Values.form.hasPage false }}
      openDrawer:
{{- range .Values.panel.widgetData.actions.openDrawer }}
        - id: {{ .id | quote }}
          resourceRefId: {{ .resourceRefId | quote }}
          type: {{ .type | quote }}
          size: {{ .size | quote }}
          title: {{ tpl $.Values.panel.widgetData.title $ | quote }}
{{- end }}
      {{- else }}
      navigate:
{{- range .Values.panel.widgetData.actions.navigate }}
        - id: {{ .id | quote }}
          path: {{ tpl .path $ | quote }}
          type: {{ .type | quote }}
{{- end }}
      {{- end }}

  widgetDataTemplate:
{{- range .Values.panel.widgetDataTemplate }}
    - forPath: {{ .forPath | quote }}
      expression: |
{{ .expression | nindent 8 }}
{{- end }}

  resourcesRefs:
    items:
{{- range .Values.panel.resourcesRefs.items }}
      - id: {{ .id | quote }}
        apiVersion: {{ .apiVersion | quote }}
        name: {{ tpl .name $ | quote }}
        namespace: {{ default $.Release.Namespace (tpl .namespace $) | quote }}
        resource: {{ .resource | quote }}
        verb: {{ .verb | quote }}
{{- end }}